---
# This task file controls the main install and delegate tasks to distro specific files
- name: INCLUDE; execute tasks specific tasks
  include: "{{ ansible_distribution }}.yml"

- name: NPM; install npm proxy
  npm:
    name: configurable-http-proxy
    global: yes

- name: PIP; upgrade pip3
  pip:
    name: pip
    state: latest
    executable: pip3

# - name: install the REMOTE_USER authenticator
#   git:
#     repo: https://github.com/cwaldbieser/jhub_remote_user_authenticator.git
#     dest: /opt/jhub_remote_user_authenticator

- name: install jupyter, jupyterhub, and other pip packages (as necessary)
  pip:
    name:
    - notebook
    - jupyterhub
    - dockerspawner
    - oauthenticator
    state: latest
    executable: pip3
  # with_items:
  #   - notebook
  #   - jupyterhub
  #   - dockerspawner
  #   - oauthenticator
  #   - /opt/jhub_remote_user_authenticator

###
# This is for apache
###
# - name: execute apache specific tasks, varies by distro
#   include: "{{ ansible_distribution }}-apache.yml"

###
# This is to initialize docker
###

- name: DOCKER_IMAGE; docker pull the jupyterhub image
  community.docker.docker_image:
    name: "{{ jupyterhub_docker_image }}:{{ jupyterhub_docker_tag }}"
    source: pull

###
# This is for the jupyterhub systemd service
###
- name: install the systemd jupyterhub service
  template:
    src: jupyterhub.service.j2
    dest: /lib/systemd/system/jupyterhub.service
    owner: root
    group: root
    mode: 0644

- name: enable the service
  systemd:
    name: jupyterhub
    enabled: yes
    state: started

- name: force restart of jupyterhub
  systemd:
    name: jupyterhub
    state: restarted
