---
# This task file controls the main install and delegate tasks to distro specific files

- name: INCLUDE_VARS; load os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"

###
# This is for jupyterhub configuration
###
- name: FILE; make/verify the jupyterhub install directory {{ jupyterhub_install_dir }}
  file:
    path: "{{ jupyterhub_install_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

  
- name: TEMPLATE; copy over the jupyterhub config
  template:
    src: jupyterhub_config.py.j2
    dest: "{{ jupyterhub_install_dir }}/jupyterhub_config.py"
    owner: root
    group: root
    mode: 0644

# This block is only if we need to link the system config
- block:
  - name: FILE; make/verify the jupyterhub system config directory
    file:
      path: "{{ jupyterhub_system_config }}"
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: FILE; link the config file iff the install dir <> system config dir
    file:
      src: "{{ jupyterhub_install_dir }}/jupyterhub_config.py"
      dest: "{{ jupyterhub_system_config }}/jupyterhub_config.py"
      state: link
      owner: root
      group: root
    when: "'{{ jupyterhub_install_dir }}' != '{{ jupyterhub_system_config }}'"
  when: not jupyterhub_enable_swarmspawner|bool
    

# invoke the spawner instructions
- name: INCLUDE; if swarmspawner
  include: swarmspawner.yml
  when: jupyterhub_enable_swarmspawner|bool

- name: INCLUDE; if docker
  include: dockerspawner.yml
  when: not jupyterhub_enable_swarmspawner|bool

###
# This is to initialize docker
###

- name: DOCKER_IMAGE; docker pull the jupyterhub image
  community.docker.docker_image:
    name: "{{ jupyterhub_docker_image }}:{{ jupyterhub_docker_tag }}"
    source: pull
